import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-inter antialiased bg-neutral-50`}>
        <NextTopLoader color="#3cbf8f" height={2} showSpinner={false} />
        {children}
      </body>
    </html>
  );
}
